# Scans assets/characters for .webp or .png layers and writes manifest.js next to this script.
# Usage (from the repo root):  powershell -ExecutionPolicy Bypass -File assets/characters/make-manifest.ps1
# Use one format only (all .webp or all .png). With no art files found, the manifest turns art off.
$root = $PSScriptRoot
$files = Get-ChildItem -Path $root -Recurse -File | Where-Object { $_.Extension -in '.webp', '.png' }
$exts = @($files | ForEach-Object { $_.Extension.TrimStart('.') } | Sort-Object -Unique)
if ($exts.Count -gt 1) { Write-Error "Mixed formats found ($($exts -join ', ')). Use one format only."; exit 1 }
$ext = if ($exts.Count -eq 1) { $exts[0] } else { 'webp' }
$rootFull = (Resolve-Path $root).Path.TrimEnd('\') + '\'
$names = @($files | ForEach-Object {
  $rel = $_.FullName.Substring($rootFull.Length).Replace('\', '/')
  $rel.Substring(0, $rel.Length - $_.Extension.Length)
} | Sort-Object)
$bad = @($names | Where-Object { $_ -notmatch '^[a-z0-9_/]+$' })
if ($bad.Count) { Write-Error "Names must be lowercase letters, digits, underscores and slashes: $($bad -join ', ')"; exit 1 }
$enabled = if ($names.Count) { 'true' } else { 'false' }
$list = ($names | ForEach-Object { "    '$_'" }) -join ",`n"
$text = @"
/* Character art manifest. Generated by make-manifest.ps1 (run it after adding or removing art files).
   enabled:false (or an empty list) means everyone is drawn in code. See assets/SPEC.md. */
window.COZY_ART = {
  enabled: $enabled,
  ext: '$ext',
  files: [
$list
  ]
};
"@
[System.IO.File]::WriteAllText((Join-Path $root 'manifest.js'), $text + "`n", (New-Object System.Text.UTF8Encoding($false)))
Write-Host "manifest.js written: $($names.Count) layers, format $ext, enabled $enabled"
